package tests;

import nlp.Rules;
import nlp.Tagger;

public class TestRules {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		Tagger tag = new Tagger();
		
		//String result = tag.testTagRules("PACIENTE COM CARDIOPATIA ISQUEMICA, ACFA COM MP, HAS, DEMENCIA, ICC FE 14%. INTERNA COM QUADRO DE SINDROME CORONARIANA AGUDA SEM SUPRA ST, TIMI 5. ENCAMINHADO PARA CAT: LESÕES DAE E CIRCUNFLEXA. REALIZADO IMPLANTE DE STENT EM DAE E CIRCUNFLEXA, SEM INTERCORRENCIAS E COM SUCESSO ANGIOGRGÁFICO. RECEBE ALTA EM USO DAS MEDICAÇÕES ABAIXO E RETORNO AO AMBU ICT P/ SEGUIMENTO.", Rules.getRules(), false);
		String result = tag.testTagRules("# DM # HAS # CRM 1988 # PROTESE DE AORTA ABDOMINAL 2000 # ANGINA REFRATARIA # CAT 06/2005: TCE COM LESAO 50% OSTIAL; ADA LIVRE; ACX OCLUIDA NA ORIGEM; PONTE SF MG PERVEA; ACD LESAO 70% DISTAL; # CINTILO 06/2005: ISQUEMIA INFERO-APICAL; # IAM C/. SSST INFERIOR: 07/2005 # ANGIOPLASTIA DE CORONÁRIA DIREITA COM COLOCAÇÃO DE STENT NESTA INTERNAÇÃO  PACIENTE PROCURA A EMERGÊNCIA COM DOR TORÁCICA TÍPICA. FOI SUBMETIDA A CATETERISMO QUE EVIDENCIA LESÃO GRAVE CD; SUBMETIDA A ANGIOPLASTIA COM COLOCAÇÃO DE STENT COM BOM RESULTADO ANGIOGRAFICO DISTAL, POREM PERMANECENDO COM LESAO PROXIMAL  DE ACD CORRESPONDENTE A ANEURISMA NAO PASSIVEL DE TTO PERCUTANEO. TEVE DOR EM SÍTIO DE PUNÇÃO NA ART. FEMORAL TENDO REALIZADO ECO DOPPLER QUE DESCARTA A PRESENÇA DE PSEUDO-ANEURISMA.  FUNCÇÃO VENTRICULAR PRESERVADA RECEBE ALTA EM BOM ESTADO GERAL E SEM DOR TORÁCICA COM TRATAMENTO CLINICO.", Rules.getRules(), false);
		
		System.out.println(result);
		System.out.println("FIM!");
		


	}

}
