package br.gpri.janelas;

public class JanelaIndices extends javax.swing.JFrame {

	    /**
	     * Creates new form Indices
	     */
	    public JanelaIndices() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {
	    	jRadioButton = new javax.swing.JRadioButton[33];
	    	for(int i=0;i<jRadioButton.length;i++)
	    		jRadioButton[i] = new javax.swing.JRadioButton();
	        
	    	GrupoTermo = new javax.swing.ButtonGroup[11];
	        for(int i=0;i<GrupoTermo.length;i++)
	        	GrupoTermo[i] = new javax.swing.ButtonGroup();
	        
	        TextoTermo = new javax.swing.JLabel[11];
	        for(int i=0; i<TextoTermo.length;i++)
	        	TextoTermo[i] = new javax.swing.JLabel();
	        
	    	
	    	
	    	
	    	
	    	jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	       

	        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

	        jLabel1.setText("INTEMED");

	        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel2.setText("Indices");
	        jLabel2.setToolTipText("");

	        BotaoOk = new javax.swing.JButton();
	        BotaoOk.setText("OK");
	        BotaoVoltar = new javax.swing.JButton();
	        BotaoVoltar.setText("VOLTAR");
	        
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(220, 220, 220)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	                    .addGroup(layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                        	.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        			.addComponent(BotaoVoltar)
	                        			.addGap(18,18,18)
	                        			.addComponent(BotaoOk))
	                            
	                            
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                                    .addComponent(TextoTermo[9], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[8], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[7], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[6], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[5], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[4], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[3], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[2], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[1], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[0], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(TextoTermo[10], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[0])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[1])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[2]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[3])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[4])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[5]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[6])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[7])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[8]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[9])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[10])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[11]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[12])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[13])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[14]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[15])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[16])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[17]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[18])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[19])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[20]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[21])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[22])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[23]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[24])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[25])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[26]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[27])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[28])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[29]))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jRadioButton[30])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[31])
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jRadioButton[32])))))))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jLabel1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jLabel2)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[0])
	                    .addComponent(jRadioButton[0])
	                    .addComponent(jRadioButton[1])
	                    .addComponent(jRadioButton[2]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[1])
	                    .addComponent(jRadioButton[3])
	                    .addComponent(jRadioButton[4])
	                    .addComponent(jRadioButton[5]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[2])
	                    .addComponent(jRadioButton[6])
	                    .addComponent(jRadioButton[7])
	                    .addComponent(jRadioButton[8]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[3])
	                    .addComponent(jRadioButton[9])
	                    .addComponent(jRadioButton[10])
	                    .addComponent(jRadioButton[11]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[4])
	                    .addComponent(jRadioButton[12])
	                    .addComponent(jRadioButton[13])
	                    .addComponent(jRadioButton[14]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[5])
	                    .addComponent(jRadioButton[15])
	                    .addComponent(jRadioButton[16])
	                    .addComponent(jRadioButton[17]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[6])
	                    .addComponent(jRadioButton[18])
	                    .addComponent(jRadioButton[19])
	                    .addComponent(jRadioButton[20]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[7])
	                    .addComponent(jRadioButton[21])
	                    .addComponent(jRadioButton[22])
	                    .addComponent(jRadioButton[23]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[8])
	                    .addComponent(jRadioButton[24])
	                    .addComponent(jRadioButton[25])
	                    .addComponent(jRadioButton[26]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[9])
	                    .addComponent(jRadioButton[27])
	                    .addComponent(jRadioButton[28])
	                    .addComponent(jRadioButton[29]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(TextoTermo[10])
	                    .addComponent(jRadioButton[30])
	                    .addComponent(jRadioButton[31])
	                    .addComponent(jRadioButton[32]))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoOk)
                    .addComponent(BotaoVoltar))
	                .addContainerGap())
	        );

	        

	        pack();
	    }// </editor-fold>                        

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(JanelaIndices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(JanelaIndices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(JanelaIndices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(JanelaIndices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new JanelaIndices().setVisible(true);
	            }
	        });
	    }
	    // Variables declaration - do not modify                     
	    public javax.swing.JButton BotaoOk;
	    public javax.swing.JButton BotaoVoltar;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;

	    
	    public javax.swing.ButtonGroup[] GrupoTermo;
	    public javax.swing.JRadioButton[] jRadioButton;
	    public javax.swing.JLabel[] TextoTermo;
	    
	    // End of variables declaration                   
	}
